// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
// biome-ignore-all lint: autogenerated file
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "fr" | "en";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	shared: {
		/**
		 * A​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​w​h​i​l​e​ ​h​a​n​d​l​i​n​g​ ​t​h​i​s​ ​i​n​t​e​r​a​c​t​i​o​n​.
		 */
		unexpected_interaction_error: string;
		/**
		 * N​o​ ​a​d​d​i​t​i​o​n​a​l​ ​d​e​t​a​i​l​s​ ​w​e​r​e​ ​p​r​o​v​i​d​e​d​.
		 */
		no_reason_provided: string;
		claim_status: {
			/**
			 * C​l​a​i​m​e​d​ ​b​y​ ​<​@​{​u​s​e​r​I​d​}​>
			 * @param {string} userId
			 */
			claimed_by: RequiredParams<"userId">;
			/**
			 * U​n​c​l​a​i​m​e​d
			 */
			unclaimed: string;
		};
		transcript_status: {
			/**
			 * [​O​p​e​n​ ​T​r​a​n​s​c​r​i​p​t​]​(​{​u​r​l​}​)
			 * @param {string} url
			 */
			ready: RequiredParams<"url">;
			/**
			 * U​n​a​v​a​i​l​a​b​l​e​ ​o​r​ ​s​t​i​l​l​ ​p​r​o​c​e​s​s​i​n​g​.
			 */
			unavailable: string;
		};
	};
	commands: {
		add: {
			/**
			 * A​d​d​ ​s​o​m​e​o​n​e​ ​t​o​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
			options: {
				user: {
					/**
					 * T​h​e​ ​u​s​e​r​ ​t​o​ ​a​d​d
					 */
					description: string;
				};
			};
			/**
			 * C​h​o​o​s​e​ ​a​ ​u​s​e​r​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			choose_user: string;
			/**
			 * T​h​a​t​ ​u​s​e​r​ ​a​l​r​e​a​d​y​ ​h​a​s​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			already_has_access: string;
			/**
			 * T​h​a​t​ ​u​s​e​r​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​v​i​t​e​d​ ​t​o​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			already_invited: string;
			/**
			 * Y​o​u​ ​c​a​n​n​o​t​ ​i​n​v​i​t​e​ ​m​o​r​e​ ​t​h​a​n​ ​{​l​i​m​i​t​}​ ​u​s​e​r​s​ ​t​o​ ​o​n​e​ ​t​i​c​k​e​t​.
			 * @param {number} limit
			 */
			invite_limit_reached: RequiredParams<"limit">;
			/**
			 * A​d​d​e​d​ ​<​@​{​u​s​e​r​I​d​}​>​ ​t​o​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 * @param {string} userId
			 */
			success: RequiredParams<"userId">;
		};
		claim: {
			/**
			 * C​l​a​i​m​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
			/**
			 * T​i​c​k​e​t​ ​c​l​a​i​m​i​n​g​ ​i​s​ ​d​i​s​a​b​l​e​d​.
			 */
			disabled: string;
			/**
			 * Y​o​u​ ​a​l​r​e​a​d​y​ ​c​l​a​i​m​e​d​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			already_claimed: string;
			/**
			 * T​h​i​s​ ​t​i​c​k​e​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​c​l​a​i​m​e​d​ ​a​n​d​ ​c​a​n​n​o​t​ ​b​e​ ​t​a​k​e​n​ ​o​v​e​r​.
			 */
			cannot_take_over: string;
			/**
			 * O​n​l​y​ ​s​t​a​f​f​ ​c​a​n​ ​c​l​a​i​m​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_staff: string;
			/**
			 * Y​o​u​ ​c​l​a​i​m​e​d​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			success: string;
			/**
			 * T​i​c​k​e​t​ ​r​e​a​s​s​i​g​n​e​d​ ​t​o​ ​<​@​{​u​s​e​r​I​d​}​>​.
			 * @param {string} userId
			 */
			reassigned: RequiredParams<"userId">;
		};
		close: {
			/**
			 * C​l​o​s​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
		};
		reopen: {
			/**
			 * R​e​o​p​e​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
		};
		cleardm: {
			/**
			 * C​l​e​a​r​ ​t​h​e​ ​b​o​t​'​s​ ​t​i​c​k​e​t​ ​h​i​s​t​o​r​y​ ​f​r​o​m​ ​y​o​u​r​ ​D​M​s
			 */
			description: string;
			/**
			 * C​l​e​a​r​i​n​g​ ​y​o​u​r​ ​t​i​c​k​e​t​ ​D​M​ ​h​i​s​t​o​r​y​.​.​.
			 */
			starting: string;
			/**
			 * I​ ​c​o​u​l​d​ ​n​o​t​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​D​M​ ​c​h​a​n​n​e​l​.
			 */
			dm_unavailable: string;
			/**
			 * C​l​e​a​r​e​d​ ​{​c​o​u​n​t​}​ ​t​i​c​k​e​t​ ​D​M​ ​m​e​s​s​a​g​e​s​.
			 * @param {number} count
			 */
			cleared: RequiredParams<"count">;
			/**
			 * N​o​ ​t​i​c​k​e​t​ ​D​M​ ​m​e​s​s​a​g​e​s​ ​w​e​r​e​ ​f​o​u​n​d​.
			 */
			none_found: string;
		};
		mass_add: {
			/**
			 * A​d​d​ ​m​u​l​t​i​p​l​e​ ​u​s​e​r​s​ ​t​o​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
			options: {
				users: {
					/**
					 * C​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​u​s​e​r​ ​I​D​s​ ​o​r​ ​m​e​n​t​i​o​n​s
					 */
					description: string;
				};
			};
			/**
			 * P​r​o​v​i​d​e​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​s​e​r​ ​I​D​ ​o​r​ ​m​e​n​t​i​o​n​.
			 */
			provide_users: string;
			summary: {
				/**
				 * A​d​d​e​d​ ​{​m​e​n​t​i​o​n​s​}​.
				 * @param {string} mentions
				 */
				added: RequiredParams<"mentions">;
				/**
				 * N​o​ ​u​s​e​r​s​ ​w​e​r​e​ ​a​d​d​e​d​.
				 */
				none_added: string;
				/**
				 * S​k​i​p​p​e​d​ ​{​c​o​u​n​t​}​ ​u​s​e​r​(​s​)​ ​t​h​a​t​ ​a​l​r​e​a​d​y​ ​h​a​d​ ​a​c​c​e​s​s​.
				 * @param {number} count
				 */
				skipped_existing: RequiredParams<"count">;
				/**
				 * S​k​i​p​p​e​d​ ​{​c​o​u​n​t​}​ ​i​n​v​a​l​i​d​ ​u​s​e​r​ ​I​D​(​s​)​.
				 * @param {number} count
				 */
				skipped_invalid: RequiredParams<"count">;
				/**
				 * S​t​o​p​p​e​d​ ​w​h​e​n​ ​t​h​e​ ​{​l​i​m​i​t​}​-​u​s​e​r​ ​t​i​c​k​e​t​ ​l​i​m​i​t​ ​w​a​s​ ​r​e​a​c​h​e​d​.
				 * @param {number} limit
				 */
				limit_reached: RequiredParams<"limit">;
			};
		};
		remove: {
			/**
			 * R​e​m​o​v​e​ ​i​n​v​i​t​e​d​ ​u​s​e​r​s​ ​f​r​o​m​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
			options: {
				user: {
					/**
					 * T​h​e​ ​i​n​v​i​t​e​d​ ​u​s​e​r​ ​t​o​ ​r​e​m​o​v​e​ ​i​m​m​e​d​i​a​t​e​l​y
					 */
					description: string;
				};
			};
			/**
			 * T​h​e​r​e​ ​a​r​e​ ​n​o​ ​i​n​v​i​t​e​d​ ​u​s​e​r​s​ ​t​o​ ​r​e​m​o​v​e​ ​f​r​o​m​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			no_invited_users: string;
			/**
			 * S​e​l​e​c​t​ ​t​h​e​ ​i​n​v​i​t​e​d​ ​u​s​e​r​s​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​m​o​v​e​ ​f​r​o​m​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			select_users: string;
			/**
			 * C​h​o​o​s​e​ ​u​s​e​r​s​ ​t​o​ ​r​e​m​o​v​e
			 */
			select_placeholder: string;
			/**
			 * T​h​o​s​e​ ​u​s​e​r​s​ ​a​r​e​ ​n​o​t​ ​i​n​v​i​t​e​d​ ​t​o​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			not_invited: string;
			/**
			 * R​e​m​o​v​e​d​ ​{​m​e​n​t​i​o​n​s​}​ ​f​r​o​m​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 * @param {string} mentions
			 */
			success: RequiredParams<"mentions">;
		};
		rename: {
			/**
			 * R​e​n​a​m​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
			options: {
				name: {
					/**
					 * T​h​e​ ​n​e​w​ ​t​i​c​k​e​t​ ​c​h​a​n​n​e​l​ ​n​a​m​e
					 */
					description: string;
				};
			};
			/**
			 * O​n​l​y​ ​s​t​a​f​f​ ​c​a​n​ ​r​e​n​a​m​e​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_staff: string;
			/**
			 * P​r​o​v​i​d​e​ ​a​ ​n​e​w​ ​t​i​c​k​e​t​ ​n​a​m​e​.
			 */
			provide_name: string;
			/**
			 * T​i​c​k​e​t​ ​r​e​n​a​m​e​d​ ​t​o​ ​<​#​{​c​h​a​n​n​e​l​I​d​}​>​.
			 * @param {string} channelId
			 */
			success: RequiredParams<"channelId">;
		};
		unclaim: {
			/**
			 * U​n​c​l​a​i​m​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​i​c​k​e​t
			 */
			description: string;
			/**
			 * U​n​c​l​a​i​m​i​n​g​ ​i​s​ ​d​i​s​a​b​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​s​e​r​v​e​r​.
			 */
			disabled: string;
			/**
			 * T​h​i​s​ ​t​i​c​k​e​t​ ​i​s​ ​n​o​t​ ​c​l​a​i​m​e​d​.
			 */
			not_claimed: string;
			/**
			 * O​n​l​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​l​a​i​m​e​r​ ​c​a​n​ ​u​n​c​l​a​i​m​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_current_claimer: string;
			/**
			 * Y​o​u​ ​u​n​c​l​a​i​m​e​d​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			success: string;
		};
	};
	tickets: {
		records: {
			/**
			 * T​h​i​s​ ​i​n​t​e​r​a​c​t​i​o​n​ ​w​a​s​ ​n​o​t​ ​u​s​e​d​ ​i​n​ ​a​ ​t​i​c​k​e​t​ ​c​h​a​n​n​e​l​.
			 */
			not_ticket_channel: string;
			/**
			 * T​h​i​s​ ​c​h​a​n​n​e​l​ ​i​s​ ​n​o​t​ ​a​n​ ​o​p​e​n​ ​t​i​c​k​e​t​.
			 */
			not_open_ticket: string;
			/**
			 * T​h​i​s​ ​t​i​c​k​e​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​c​l​o​s​e​d​.
			 */
			already_closed: string;
		};
		panel: {
			/**
			 * Y​o​u​ ​d​o​ ​n​o​t​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​a​n​y​ ​t​i​c​k​e​t​ ​t​y​p​e​s​ ​o​n​ ​t​h​i​s​ ​p​a​n​e​l​.
			 */
			no_visible_types: string;
			/**
			 * P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​t​i​c​k​e​t​ ​t​y​p​e​.
			 */
			select_type: string;
			/**
			 * T​h​a​t​ ​t​i​c​k​e​t​ ​t​y​p​e​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​f​r​o​m​ ​t​h​i​s​ ​p​a​n​e​l​.
			 */
			unavailable_type: string;
			/**
			 * S​e​l​e​c​t​ ​a​ ​t​i​c​k​e​t​ ​t​y​p​e
			 */
			select_placeholder: string;
		};
		open: {
			/**
			 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​a​l​l​o​w​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​h​a​t​ ​t​i​c​k​e​t​ ​t​y​p​e​.
			 */
			not_allowed_type: string;
			/**
			 * T​h​a​t​ ​t​i​c​k​e​t​ ​t​y​p​e​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​f​r​o​m​ ​t​h​i​s​ ​p​a​n​e​l​.
			 */
			unavailable_type: string;
			/**
			 * Y​o​u​ ​a​l​r​e​a​d​y​ ​h​a​v​e​ ​t​h​e​ ​m​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​o​p​e​n​ ​t​i​c​k​e​t​s​ ​(​{​l​i​m​i​t​}​)​.
			 * @param {number} limit
			 */
			max_open_reached: RequiredParams<"limit">;
			/**
			 * Y​o​u​r​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​r​e​a​t​e​d​:​ ​<​#​{​c​h​a​n​n​e​l​I​d​}​>
			 * @param {string} channelId
			 */
			created: RequiredParams<"channelId">;
			/**
			 * {​l​a​b​e​l​}​:​ ​{​a​n​s​w​e​r​}
			 * @param {string} answer
			 * @param {string} label
			 */
			question_answer: RequiredParams<"answer" | "label">;
		};
		claim: {
			/**
			 * O​n​l​y​ ​s​t​a​f​f​ ​c​a​n​ ​c​l​a​i​m​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_staff: string;
		};
		actions: {
			/**
			 * C​l​o​s​e​ ​T​i​c​k​e​t
			 */
			close_ticket: string;
			/**
			 * R​e​o​p​e​n​ ​T​i​c​k​e​t
			 */
			reopen_ticket: string;
			/**
			 * C​l​a​i​m​ ​T​i​c​k​e​t
			 */
			claim_ticket: string;
			/**
			 * U​n​c​l​a​i​m​ ​T​i​c​k​e​t
			 */
			unclaim_ticket: string;
			/**
			 * D​e​l​e​t​e​ ​T​i​c​k​e​t
			 */
			delete_ticket: string;
		};
		close: {
			/**
			 * D​e​l​e​t​i​n​g​ ​t​i​c​k​e​t​ ​c​h​a​n​n​e​l​.​.​.
			 */
			delete_channel_start: string;
			modal: {
				/**
				 * C​l​o​s​e​ ​T​i​c​k​e​t
				 */
				title: string;
				/**
				 * R​e​a​s​o​n
				 */
				reason_label: string;
				/**
				 * W​h​y​ ​i​s​ ​t​h​i​s​ ​t​i​c​k​e​t​ ​b​e​i​n​g​ ​c​l​o​s​e​d​?
				 */
				reason_placeholder: string;
			};
			status: {
				/**
				 * P​r​e​p​a​r​i​n​g​ ​t​r​a​n​s​c​r​i​p​t​.​.​.
				 */
				preparing_transcript: string;
				/**
				 * C​l​o​s​i​n​g​ ​t​i​c​k​e​t​.​.​.
				 */
				closing_ticket: string;
				/**
				 * U​p​d​a​t​i​n​g​ ​t​i​c​k​e​t​ ​a​c​c​e​s​s​.​.​.
				 */
				updating_access: string;
				/**
				 * T​r​a​n​s​c​r​i​p​t​ ​i​s​ ​s​t​i​l​l​ ​p​r​o​c​e​s​s​i​n​g​.​ ​F​i​n​i​s​h​i​n​g​ ​t​i​c​k​e​t​ ​c​l​o​s​e​.​.​.
				 */
				transcript_still_processing: string;
				/**
				 * S​e​n​d​i​n​g​ ​c​l​o​s​e​ ​c​o​n​f​i​r​m​a​t​i​o​n​.​.​.
				 */
				sending_close_confirmation: string;
				/**
				 * S​e​n​d​i​n​g​ ​c​l​o​s​e​ ​u​p​d​a​t​e​s​.​.​.
				 */
				sending_close_updates: string;
				/**
				 * P​o​s​t​i​n​g​ ​c​l​o​s​e​ ​s​u​m​m​a​r​y​.​.​.
				 */
				posting_close_summary: string;
				/**
				 * T​i​c​k​e​t​ ​c​l​o​s​e​d​.
				 */
				closed: string;
			};
			/**
			 * T​i​c​k​e​t​ ​c​l​o​s​e​d​.​ ​T​h​e​ ​t​r​a​n​s​c​r​i​p​t​ ​i​s​ ​r​e​a​d​y​ ​a​n​d​ ​t​h​e​ ​c​h​a​n​n​e​l​ ​w​i​l​l​ ​n​o​w​ ​b​e​ ​d​e​l​e​t​e​d​.
			 */
			deleted_with_transcript: string;
			/**
			 * T​i​c​k​e​t​ ​c​l​o​s​e​d​.​ ​T​h​e​ ​c​h​a​n​n​e​l​ ​w​i​l​l​ ​n​o​w​ ​b​e​ ​d​e​l​e​t​e​d​.
			 */
			deleted_without_transcript: string;
			/**
			 * O​n​l​y​ ​s​t​a​f​f​ ​c​a​n​ ​c​l​o​s​e​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_staff: string;
			/**
			 * T​h​i​s​ ​t​i​c​k​e​t​ ​m​u​s​t​ ​b​e​ ​c​l​a​i​m​e​d​ ​b​e​f​o​r​e​ ​i​t​ ​c​a​n​ ​b​e​ ​c​l​o​s​e​d​.
			 */
			must_be_claimed: string;
			/**
			 * O​n​l​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​l​a​i​m​e​r​ ​c​a​n​ ​c​l​o​s​e​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_current_claimer: string;
			/**
			 * T​h​i​s​ ​c​h​a​n​n​e​l​ ​i​s​ ​n​o​t​ ​a​ ​t​i​c​k​e​t​.
			 */
			not_ticket: string;
			/**
			 * O​n​l​y​ ​c​l​o​s​e​d​ ​t​i​c​k​e​t​s​ ​c​a​n​ ​b​e​ ​d​e​l​e​t​e​d​ ​f​r​o​m​ ​t​h​i​s​ ​b​u​t​t​o​n​.
			 */
			only_closed_delete: string;
			/**
			 * O​n​l​y​ ​s​t​a​f​f​ ​c​a​n​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_staff_delete: string;
		};
		reopen: {
			/**
			 * T​h​i​s​ ​c​h​a​n​n​e​l​ ​i​s​ ​n​o​t​ ​a​ ​t​i​c​k​e​t​.
			 */
			not_ticket: string;
			/**
			 * O​n​l​y​ ​c​l​o​s​e​d​ ​t​i​c​k​e​t​s​ ​c​a​n​ ​b​e​ ​r​e​o​p​e​n​e​d​.
			 */
			only_closed: string;
			/**
			 * O​n​l​y​ ​s​t​a​f​f​ ​c​a​n​ ​r​e​o​p​e​n​ ​t​h​i​s​ ​t​i​c​k​e​t​.
			 */
			only_staff: string;
			/**
			 * T​i​c​k​e​t​ ​r​e​o​p​e​n​e​d​.​ ​P​a​r​t​i​c​i​p​a​n​t​ ​a​c​c​e​s​s​ ​a​n​d​ ​t​i​c​k​e​t​ ​a​c​t​i​o​n​s​ ​h​a​v​e​ ​b​e​e​n​ ​r​e​s​t​o​r​e​d​.
			 */
			success: string;
		};
		transcript: {
			/**
			 * C​o​l​l​e​c​t​i​n​g​ ​t​i​c​k​e​t​ ​m​e​s​s​a​g​e​s​.​.​.
			 */
			collecting_messages: string;
			/**
			 * C​r​e​a​t​i​n​g​ ​t​r​a​n​s​c​r​i​p​t​.​.​.
			 */
			creating: string;
			/**
			 * U​p​l​o​a​d​i​n​g​ ​t​r​a​n​s​c​r​i​p​t​.​.​.
			 */
			uploading: string;
			/**
			 * U​p​l​o​a​d​i​n​g​ ​a​v​a​t​a​r​s​.​.​.
			 */
			uploading_avatars: string;
			/**
			 * U​p​l​o​a​d​i​n​g​ ​a​t​t​a​c​h​m​e​n​t​s​.​.​.
			 */
			uploading_attachments: string;
			/**
			 * {​l​a​b​e​l​}​ ​(​{​c​o​m​p​l​e​t​e​d​}​/​{​t​o​t​a​l​}​)
			 * @param {number} completed
			 * @param {string} label
			 * @param {number} total
			 */
			progress: RequiredParams<"completed" | "label" | "total">;
		};
		templates: {
			open_panel: {
				/**
				 * #​#​ ​O​p​e​n​ ​a​ ​T​i​c​k​e​t
				 */
				title: string;
				/**
				 * C​h​o​o​s​e​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​t​h​a​t​ ​m​a​t​c​h​e​s​ ​y​o​u​r​ ​r​e​q​u​e​s​t​ ​a​n​d​ ​t​h​e​ ​b​o​t​ ​w​i​l​l​ ​c​r​e​a​t​e​ ​a​ ​p​r​i​v​a​t​e​ ​t​i​c​k​e​t​ ​f​o​r​ ​y​o​u​.
				 */
				description: string;
			};
			ticket_opened: {
				/**
				 * #​#​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​ ​T​i​c​k​e​t
				 * @param {string} ticketTypeName
				 */
				title: RequiredParams<"ticketTypeName">;
				/**
				 * T​h​a​n​k​s​ ​f​o​r​ ​o​p​e​n​i​n​g​ ​a​ ​t​i​c​k​e​t​.
				 */
				intro: string;
				/**
				 * *​*​D​e​t​a​i​l​s​*​*​
			​{​r​e​a​s​o​n​}
				 * @param {string} reason
				 */
				details_label: RequiredParams<"reason">;
				/**
				 * *​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 */
				claim_status: RequiredParams<"claimStatus">;
			};
			ticket_opened_general: {
				/**
				 * #​#​ ​G​e​n​e​r​a​l​ ​S​u​p​p​o​r​t​ ​T​i​c​k​e​t
				 */
				title: string;
				/**
				 * A​ ​s​u​p​p​o​r​t​ ​t​e​a​m​ ​m​e​m​b​e​r​ ​w​i​l​l​ ​r​e​v​i​e​w​ ​t​h​i​s​ ​r​e​q​u​e​s​t​ ​s​o​o​n​.
				 */
				intro: string;
				/**
				 * *​*​S​u​m​m​a​r​y​*​*​
			​{​r​e​a​s​o​n​}
				 * @param {string} reason
				 */
				details_label: RequiredParams<"reason">;
				/**
				 * *​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 */
				claim_status: RequiredParams<"claimStatus">;
			};
			ticket_opened_billing: {
				/**
				 * #​#​ ​B​i​l​l​i​n​g​ ​T​i​c​k​e​t
				 */
				title: string;
				/**
				 * I​n​c​l​u​d​e​ ​i​n​v​o​i​c​e​ ​n​u​m​b​e​r​s​,​ ​p​a​y​m​e​n​t​ ​m​e​t​h​o​d​,​ ​a​n​d​ ​a​n​y​ ​f​a​i​l​e​d​ ​t​r​a​n​s​a​c​t​i​o​n​ ​d​e​t​a​i​l​s​.
				 */
				intro: string;
				/**
				 * *​*​S​u​b​m​i​t​t​e​d​ ​D​e​t​a​i​l​s​*​*​
			​{​r​e​a​s​o​n​}
				 * @param {string} reason
				 */
				details_label: RequiredParams<"reason">;
				/**
				 * *​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 */
				claim_status: RequiredParams<"claimStatus">;
			};
			ticket_opened_report: {
				/**
				 * #​#​ ​R​e​p​o​r​t​ ​T​i​c​k​e​t
				 */
				title: string;
				/**
				 * M​o​d​e​r​a​t​i​o​n​ ​s​t​a​f​f​ ​w​i​l​l​ ​r​e​v​i​e​w​ ​t​h​e​ ​r​e​p​o​r​t​ ​a​n​d​ ​a​n​y​ ​e​v​i​d​e​n​c​e​ ​a​t​t​a​c​h​e​d​.
				 */
				intro: string;
				/**
				 * *​*​R​e​p​o​r​t​ ​D​e​t​a​i​l​s​*​*​
			​{​r​e​a​s​o​n​}
				 * @param {string} reason
				 */
				details_label: RequiredParams<"reason">;
				/**
				 * *​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 */
				claim_status: RequiredParams<"claimStatus">;
			};
			ticket_closed: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​C​l​o​s​e​d
				 */
				title: string;
				/**
				 * <​@​{​u​s​e​r​I​d​}​>​'​s​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d​.
				 * @param {string} userId
				 */
				subtitle: RequiredParams<"userId">;
				/**
				 * *​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_general: {
				/**
				 * #​#​ ​G​e​n​e​r​a​l​ ​S​u​p​p​o​r​t​ ​C​l​o​s​e​d
				 */
				title: string;
				/**
				 * <​@​{​u​s​e​r​I​d​}​>​'​s​ ​g​e​n​e​r​a​l​ ​s​u​p​p​o​r​t​ ​t​i​c​k​e​t​ ​i​s​ ​n​o​w​ ​c​l​o​s​e​d​.
				 * @param {string} userId
				 */
				subtitle: RequiredParams<"userId">;
				/**
				 * *​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_billing: {
				/**
				 * #​#​ ​B​i​l​l​i​n​g​ ​T​i​c​k​e​t​ ​C​l​o​s​e​d
				 */
				title: string;
				/**
				 * <​@​{​u​s​e​r​I​d​}​>​'​s​ ​b​i​l​l​i​n​g​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d​.
				 * @param {string} userId
				 */
				subtitle: RequiredParams<"userId">;
				/**
				 * *​*​C​l​o​s​e​ ​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_report: {
				/**
				 * #​#​ ​R​e​p​o​r​t​ ​C​a​s​e​ ​C​l​o​s​e​d
				 */
				title: string;
				/**
				 * T​h​e​ ​r​e​p​o​r​t​ ​o​p​e​n​e​d​ ​b​y​ ​<​@​{​u​s​e​r​I​d​}​>​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d​.
				 * @param {string} userId
				 */
				subtitle: RequiredParams<"userId">;
				/**
				 * *​*​R​e​s​o​l​u​t​i​o​n​ ​N​o​t​e​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_dm: {
				/**
				 * #​#​ ​Y​o​u​r​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d
				 */
				title: string;
				/**
				 * *​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_dm_general: {
				/**
				 * #​#​ ​Y​o​u​r​ ​g​e​n​e​r​a​l​ ​s​u​p​p​o​r​t​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d
				 */
				title: string;
				/**
				 * *​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_dm_billing: {
				/**
				 * #​#​ ​Y​o​u​r​ ​b​i​l​l​i​n​g​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d
				 */
				title: string;
				/**
				 * I​f​ ​y​o​u​ ​s​t​i​l​l​ ​n​e​e​d​ ​h​e​l​p​,​ ​o​p​e​n​ ​a​ ​n​e​w​ ​b​i​l​l​i​n​g​ ​t​i​c​k​e​t​ ​a​n​d​ ​i​n​c​l​u​d​e​ ​y​o​u​r​ ​o​r​d​e​r​ ​d​e​t​a​i​l​s​ ​a​g​a​i​n​.
				 */
				intro: string;
				/**
				 * *​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
			ticket_closed_dm_report: {
				/**
				 * #​#​ ​Y​o​u​r​ ​r​e​p​o​r​t​ ​t​i​c​k​e​t​ ​h​a​s​ ​b​e​e​n​ ​c​l​o​s​e​d
				 */
				title: string;
				/**
				 * S​t​a​f​f​ ​r​e​v​i​e​w​e​d​ ​t​h​e​ ​r​e​p​o​r​t​ ​a​n​d​ ​a​n​y​ ​a​t​t​a​c​h​e​d​ ​e​v​i​d​e​n​c​e​.
				 */
				intro: string;
				/**
				 * *​*​R​e​s​o​l​u​t​i​o​n​ ​N​o​t​e​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​C​l​a​i​m​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} reason
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<"claimStatus" | "reason" | "transcriptStatus">;
				/**
				 * -​#​ ​_​C​l​o​s​e​d​ ​b​y​ ​{​c​l​o​s​e​r​N​a​m​e​}​_
				 * @param {string} closerName
				 */
				closed_by: RequiredParams<"closerName">;
			};
		};
	};
	logs: {
		duration: {
			/**
			 * d
			 */
			day_short: string;
			/**
			 * h
			 */
			hour_short: string;
			/**
			 * m
			 */
			minute_short: string;
			/**
			 * s
			 */
			second_short: string;
		};
		templates: {
			ticket_created: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​C​r​e​a​t​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​o​p​e​n​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​C​r​e​a​t​e​d​*​*​:​ ​{​c​r​e​a​t​e​d​A​t​}​
			​*​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}
				 * @param {string} createdAt
				 * @param {string} createdByMention
				 * @param {string} reason
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"createdAt" | "createdByMention" | "reason" | "ticketId" | "ticketTypeName">;
			};
			ticket_claimed: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​C​l​a​i​m​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​c​l​a​i​m​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​O​p​e​n​ ​A​g​e​*​*​:​ ​{​t​i​c​k​e​t​A​g​e​}
				 * @param {string} createdByMention
				 * @param {string} ticketAge
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"createdByMention" | "ticketAge" | "ticketId" | "ticketTypeName">;
			};
			ticket_unclaimed: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​U​n​c​l​a​i​m​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​u​n​c​l​a​i​m​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​O​p​e​n​ ​A​g​e​*​*​:​ ​{​t​i​c​k​e​t​A​g​e​}
				 * @param {string} createdByMention
				 * @param {string} ticketAge
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"createdByMention" | "ticketAge" | "ticketId" | "ticketTypeName">;
			};
			ticket_closed: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​C​l​o​s​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​c​l​o​s​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​O​p​e​n​ ​A​g​e​*​*​:​ ​{​t​i​c​k​e​t​A​g​e​}​
			​*​*​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} createdByMention
				 * @param {string} reason
				 * @param {string} ticketAge
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<
					"claimStatus" | "createdByMention" | "reason" | "ticketAge" | "ticketId" | "ticketTypeName" | "transcriptStatus"
				>;
			};
			ticket_reopened: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​R​e​o​p​e​n​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​r​e​o​p​e​n​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​T​i​c​k​e​t​ ​A​g​e​*​*​:​ ​{​t​i​c​k​e​t​A​g​e​}
				 * @param {string} claimStatus
				 * @param {string} createdByMention
				 * @param {string} ticketAge
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"claimStatus" | "createdByMention" | "ticketAge" | "ticketId" | "ticketTypeName">;
			};
			ticket_deleted: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​D​e​l​e​t​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​d​e​l​e​t​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​C​l​a​i​m​ ​S​t​a​t​u​s​*​*​:​ ​{​c​l​a​i​m​S​t​a​t​u​s​}​
			​*​*​O​p​e​n​ ​A​g​e​*​*​:​ ​{​t​i​c​k​e​t​A​g​e​}​
			​*​*​C​l​o​s​e​ ​R​e​a​s​o​n​*​*​:​ ​{​r​e​a​s​o​n​}​
			​*​*​T​r​a​n​s​c​r​i​p​t​*​*​:​ ​{​t​r​a​n​s​c​r​i​p​t​S​t​a​t​u​s​}
				 * @param {string} claimStatus
				 * @param {string} createdByMention
				 * @param {string} reason
				 * @param {string} ticketAge
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 * @param {string} transcriptStatus
				 */
				details: RequiredParams<
					"claimStatus" | "createdByMention" | "reason" | "ticketAge" | "ticketId" | "ticketTypeName" | "transcriptStatus"
				>;
			};
			ticket_renamed: {
				/**
				 * #​#​ ​T​i​c​k​e​t​ ​R​e​n​a​m​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​r​e​n​a​m​e​d​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}​
			​*​*​F​r​o​m​*​*​:​ ​`​{​o​l​d​C​h​a​n​n​e​l​N​a​m​e​}​`​
			​*​*​T​o​*​*​:​ ​`​{​n​e​w​C​h​a​n​n​e​l​N​a​m​e​}​`
				 * @param {string} createdByMention
				 * @param {string} newChannelName
				 * @param {string} oldChannelName
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"createdByMention" | "newChannelName" | "oldChannelName" | "ticketId" | "ticketTypeName">;
			};
			user_added: {
				/**
				 * #​#​ ​U​s​e​r​ ​A​d​d​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​a​d​d​e​d​ ​{​t​a​r​g​e​t​M​e​n​t​i​o​n​}​ ​t​o​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} targetMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "targetMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}
				 * @param {string} createdByMention
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"createdByMention" | "ticketId" | "ticketTypeName">;
			};
			user_removed: {
				/**
				 * #​#​ ​U​s​e​r​ ​R​e​m​o​v​e​d
				 */
				title: string;
				/**
				 * {​a​c​t​o​r​M​e​n​t​i​o​n​}​ ​r​e​m​o​v​e​d​ ​{​t​a​r​g​e​t​M​e​n​t​i​o​n​}​ ​f​r​o​m​ ​{​t​i​c​k​e​t​C​h​a​n​n​e​l​M​e​n​t​i​o​n​}​.
				 * @param {string} actorMention
				 * @param {string} targetMention
				 * @param {string} ticketChannelMention
				 */
				action: RequiredParams<"actorMention" | "targetMention" | "ticketChannelMention">;
				/**
				 * *​*​T​i​c​k​e​t​*​*​:​ ​#​{​t​i​c​k​e​t​I​d​}​ ​-​ ​{​t​i​c​k​e​t​T​y​p​e​N​a​m​e​}​
			​*​*​O​p​e​n​e​d​ ​B​y​*​*​:​ ​{​c​r​e​a​t​e​d​B​y​M​e​n​t​i​o​n​}
				 * @param {string} createdByMention
				 * @param {string} ticketId
				 * @param {string} ticketTypeName
				 */
				details: RequiredParams<"createdByMention" | "ticketId" | "ticketTypeName">;
			};
		};
	};
};

export type TranslationFunctions = {
	shared: {
		/**
		 * An unexpected error occurred while handling this interaction.
		 */
		unexpected_interaction_error: () => LocalizedString;
		/**
		 * No additional details were provided.
		 */
		no_reason_provided: () => LocalizedString;
		claim_status: {
			/**
			 * Claimed by <@{userId}>
			 */
			claimed_by: (arg: { userId: string }) => LocalizedString;
			/**
			 * Unclaimed
			 */
			unclaimed: () => LocalizedString;
		};
		transcript_status: {
			/**
			 * [Open Transcript]({url})
			 */
			ready: (arg: { url: string }) => LocalizedString;
			/**
			 * Unavailable or still processing.
			 */
			unavailable: () => LocalizedString;
		};
	};
	commands: {
		add: {
			/**
			 * Add someone to the current ticket
			 */
			description: () => LocalizedString;
			options: {
				user: {
					/**
					 * The user to add
					 */
					description: () => LocalizedString;
				};
			};
			/**
			 * Choose a user to add to this ticket.
			 */
			choose_user: () => LocalizedString;
			/**
			 * That user already has access to this ticket.
			 */
			already_has_access: () => LocalizedString;
			/**
			 * That user is already invited to this ticket.
			 */
			already_invited: () => LocalizedString;
			/**
			 * You cannot invite more than {limit} users to one ticket.
			 */
			invite_limit_reached: (arg: { limit: number }) => LocalizedString;
			/**
			 * Added <@{userId}> to this ticket.
			 */
			success: (arg: { userId: string }) => LocalizedString;
		};
		claim: {
			/**
			 * Claim the current ticket
			 */
			description: () => LocalizedString;
			/**
			 * Ticket claiming is disabled.
			 */
			disabled: () => LocalizedString;
			/**
			 * You already claimed this ticket.
			 */
			already_claimed: () => LocalizedString;
			/**
			 * This ticket is already claimed and cannot be taken over.
			 */
			cannot_take_over: () => LocalizedString;
			/**
			 * Only staff can claim this ticket.
			 */
			only_staff: () => LocalizedString;
			/**
			 * You claimed this ticket.
			 */
			success: () => LocalizedString;
			/**
			 * Ticket reassigned to <@{userId}>.
			 */
			reassigned: (arg: { userId: string }) => LocalizedString;
		};
		close: {
			/**
			 * Close the current ticket
			 */
			description: () => LocalizedString;
		};
		reopen: {
			/**
			 * Reopen the current ticket
			 */
			description: () => LocalizedString;
		};
		cleardm: {
			/**
			 * Clear the bot's ticket history from your DMs
			 */
			description: () => LocalizedString;
			/**
			 * Clearing your ticket DM history...
			 */
			starting: () => LocalizedString;
			/**
			 * I could not access your DM channel.
			 */
			dm_unavailable: () => LocalizedString;
			/**
			 * Cleared {count} ticket DM messages.
			 */
			cleared: (arg: { count: number }) => LocalizedString;
			/**
			 * No ticket DM messages were found.
			 */
			none_found: () => LocalizedString;
		};
		mass_add: {
			/**
			 * Add multiple users to the current ticket
			 */
			description: () => LocalizedString;
			options: {
				users: {
					/**
					 * Comma-separated user IDs or mentions
					 */
					description: () => LocalizedString;
				};
			};
			/**
			 * Provide at least one user ID or mention.
			 */
			provide_users: () => LocalizedString;
			summary: {
				/**
				 * Added {mentions}.
				 */
				added: (arg: { mentions: string }) => LocalizedString;
				/**
				 * No users were added.
				 */
				none_added: () => LocalizedString;
				/**
				 * Skipped {count} user(s) that already had access.
				 */
				skipped_existing: (arg: { count: number }) => LocalizedString;
				/**
				 * Skipped {count} invalid user ID(s).
				 */
				skipped_invalid: (arg: { count: number }) => LocalizedString;
				/**
				 * Stopped when the {limit}-user ticket limit was reached.
				 */
				limit_reached: (arg: { limit: number }) => LocalizedString;
			};
		};
		remove: {
			/**
			 * Remove invited users from the current ticket
			 */
			description: () => LocalizedString;
			options: {
				user: {
					/**
					 * The invited user to remove immediately
					 */
					description: () => LocalizedString;
				};
			};
			/**
			 * There are no invited users to remove from this ticket.
			 */
			no_invited_users: () => LocalizedString;
			/**
			 * Select the invited users you want to remove from this ticket.
			 */
			select_users: () => LocalizedString;
			/**
			 * Choose users to remove
			 */
			select_placeholder: () => LocalizedString;
			/**
			 * Those users are not invited to this ticket.
			 */
			not_invited: () => LocalizedString;
			/**
			 * Removed {mentions} from this ticket.
			 */
			success: (arg: { mentions: string }) => LocalizedString;
		};
		rename: {
			/**
			 * Rename the current ticket
			 */
			description: () => LocalizedString;
			options: {
				name: {
					/**
					 * The new ticket channel name
					 */
					description: () => LocalizedString;
				};
			};
			/**
			 * Only staff can rename this ticket.
			 */
			only_staff: () => LocalizedString;
			/**
			 * Provide a new ticket name.
			 */
			provide_name: () => LocalizedString;
			/**
			 * Ticket renamed to <#{channelId}>.
			 */
			success: (arg: { channelId: string }) => LocalizedString;
		};
		unclaim: {
			/**
			 * Unclaim the current ticket
			 */
			description: () => LocalizedString;
			/**
			 * Unclaiming is disabled for this server.
			 */
			disabled: () => LocalizedString;
			/**
			 * This ticket is not claimed.
			 */
			not_claimed: () => LocalizedString;
			/**
			 * Only the current claimer can unclaim this ticket.
			 */
			only_current_claimer: () => LocalizedString;
			/**
			 * You unclaimed this ticket.
			 */
			success: () => LocalizedString;
		};
	};
	tickets: {
		records: {
			/**
			 * This interaction was not used in a ticket channel.
			 */
			not_ticket_channel: () => LocalizedString;
			/**
			 * This channel is not an open ticket.
			 */
			not_open_ticket: () => LocalizedString;
			/**
			 * This ticket is already closed.
			 */
			already_closed: () => LocalizedString;
		};
		panel: {
			/**
			 * You do not have access to any ticket types on this panel.
			 */
			no_visible_types: () => LocalizedString;
			/**
			 * Please select a ticket type.
			 */
			select_type: () => LocalizedString;
			/**
			 * That ticket type is not available from this panel.
			 */
			unavailable_type: () => LocalizedString;
			/**
			 * Select a ticket type
			 */
			select_placeholder: () => LocalizedString;
		};
		open: {
			/**
			 * You are not allowed to create that ticket type.
			 */
			not_allowed_type: () => LocalizedString;
			/**
			 * That ticket type is not available from this panel.
			 */
			unavailable_type: () => LocalizedString;
			/**
			 * You already have the maximum number of open tickets ({limit}).
			 */
			max_open_reached: (arg: { limit: number }) => LocalizedString;
			/**
			 * Your ticket has been created: <#{channelId}>
			 */
			created: (arg: { channelId: string }) => LocalizedString;
			/**
			 * {label}: {answer}
			 */
			question_answer: (arg: { answer: string; label: string }) => LocalizedString;
		};
		claim: {
			/**
			 * Only staff can claim this ticket.
			 */
			only_staff: () => LocalizedString;
		};
		actions: {
			/**
			 * Close Ticket
			 */
			close_ticket: () => LocalizedString;
			/**
			 * Reopen Ticket
			 */
			reopen_ticket: () => LocalizedString;
			/**
			 * Claim Ticket
			 */
			claim_ticket: () => LocalizedString;
			/**
			 * Unclaim Ticket
			 */
			unclaim_ticket: () => LocalizedString;
			/**
			 * Delete Ticket
			 */
			delete_ticket: () => LocalizedString;
		};
		close: {
			/**
			 * Deleting ticket channel...
			 */
			delete_channel_start: () => LocalizedString;
			modal: {
				/**
				 * Close Ticket
				 */
				title: () => LocalizedString;
				/**
				 * Reason
				 */
				reason_label: () => LocalizedString;
				/**
				 * Why is this ticket being closed?
				 */
				reason_placeholder: () => LocalizedString;
			};
			status: {
				/**
				 * Preparing transcript...
				 */
				preparing_transcript: () => LocalizedString;
				/**
				 * Closing ticket...
				 */
				closing_ticket: () => LocalizedString;
				/**
				 * Updating ticket access...
				 */
				updating_access: () => LocalizedString;
				/**
				 * Transcript is still processing. Finishing ticket close...
				 */
				transcript_still_processing: () => LocalizedString;
				/**
				 * Sending close confirmation...
				 */
				sending_close_confirmation: () => LocalizedString;
				/**
				 * Sending close updates...
				 */
				sending_close_updates: () => LocalizedString;
				/**
				 * Posting close summary...
				 */
				posting_close_summary: () => LocalizedString;
				/**
				 * Ticket closed.
				 */
				closed: () => LocalizedString;
			};
			/**
			 * Ticket closed. The transcript is ready and the channel will now be deleted.
			 */
			deleted_with_transcript: () => LocalizedString;
			/**
			 * Ticket closed. The channel will now be deleted.
			 */
			deleted_without_transcript: () => LocalizedString;
			/**
			 * Only staff can close this ticket.
			 */
			only_staff: () => LocalizedString;
			/**
			 * This ticket must be claimed before it can be closed.
			 */
			must_be_claimed: () => LocalizedString;
			/**
			 * Only the current claimer can close this ticket.
			 */
			only_current_claimer: () => LocalizedString;
			/**
			 * This channel is not a ticket.
			 */
			not_ticket: () => LocalizedString;
			/**
			 * Only closed tickets can be deleted from this button.
			 */
			only_closed_delete: () => LocalizedString;
			/**
			 * Only staff can delete this ticket.
			 */
			only_staff_delete: () => LocalizedString;
		};
		reopen: {
			/**
			 * This channel is not a ticket.
			 */
			not_ticket: () => LocalizedString;
			/**
			 * Only closed tickets can be reopened.
			 */
			only_closed: () => LocalizedString;
			/**
			 * Only staff can reopen this ticket.
			 */
			only_staff: () => LocalizedString;
			/**
			 * Ticket reopened. Participant access and ticket actions have been restored.
			 */
			success: () => LocalizedString;
		};
		transcript: {
			/**
			 * Collecting ticket messages...
			 */
			collecting_messages: () => LocalizedString;
			/**
			 * Creating transcript...
			 */
			creating: () => LocalizedString;
			/**
			 * Uploading transcript...
			 */
			uploading: () => LocalizedString;
			/**
			 * Uploading avatars...
			 */
			uploading_avatars: () => LocalizedString;
			/**
			 * Uploading attachments...
			 */
			uploading_attachments: () => LocalizedString;
			/**
			 * {label} ({completed}/{total})
			 */
			progress: (arg: { completed: number; label: string; total: number }) => LocalizedString;
		};
		templates: {
			open_panel: {
				/**
				 * ## Open a Ticket
				 */
				title: () => LocalizedString;
				/**
				 * Choose the category that matches your request and the bot will create a private ticket for you.
				 */
				description: () => LocalizedString;
			};
			ticket_opened: {
				/**
				 * ## {ticketTypeName} Ticket
				 */
				title: (arg: { ticketTypeName: string }) => LocalizedString;
				/**
				 * Thanks for opening a ticket.
				 */
				intro: () => LocalizedString;
				/**
				 * **Details**
			{reason}
				 */
				details_label: (arg: { reason: string }) => LocalizedString;
				/**
				 * **Claim Status**: {claimStatus}
				 */
				claim_status: (arg: { claimStatus: string }) => LocalizedString;
			};
			ticket_opened_general: {
				/**
				 * ## General Support Ticket
				 */
				title: () => LocalizedString;
				/**
				 * A support team member will review this request soon.
				 */
				intro: () => LocalizedString;
				/**
				 * **Summary**
			{reason}
				 */
				details_label: (arg: { reason: string }) => LocalizedString;
				/**
				 * **Claim Status**: {claimStatus}
				 */
				claim_status: (arg: { claimStatus: string }) => LocalizedString;
			};
			ticket_opened_billing: {
				/**
				 * ## Billing Ticket
				 */
				title: () => LocalizedString;
				/**
				 * Include invoice numbers, payment method, and any failed transaction details.
				 */
				intro: () => LocalizedString;
				/**
				 * **Submitted Details**
			{reason}
				 */
				details_label: (arg: { reason: string }) => LocalizedString;
				/**
				 * **Claim Status**: {claimStatus}
				 */
				claim_status: (arg: { claimStatus: string }) => LocalizedString;
			};
			ticket_opened_report: {
				/**
				 * ## Report Ticket
				 */
				title: () => LocalizedString;
				/**
				 * Moderation staff will review the report and any evidence attached.
				 */
				intro: () => LocalizedString;
				/**
				 * **Report Details**
			{reason}
				 */
				details_label: (arg: { reason: string }) => LocalizedString;
				/**
				 * **Claim Status**: {claimStatus}
				 */
				claim_status: (arg: { claimStatus: string }) => LocalizedString;
			};
			ticket_closed: {
				/**
				 * ## Ticket Closed
				 */
				title: () => LocalizedString;
				/**
				 * <@{userId}>'s ticket has been closed.
				 */
				subtitle: (arg: { userId: string }) => LocalizedString;
				/**
				 * **Reason**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_general: {
				/**
				 * ## General Support Closed
				 */
				title: () => LocalizedString;
				/**
				 * <@{userId}>'s general support ticket is now closed.
				 */
				subtitle: (arg: { userId: string }) => LocalizedString;
				/**
				 * **Reason**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_billing: {
				/**
				 * ## Billing Ticket Closed
				 */
				title: () => LocalizedString;
				/**
				 * <@{userId}>'s billing ticket has been closed.
				 */
				subtitle: (arg: { userId: string }) => LocalizedString;
				/**
				 * **Close Reason**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_report: {
				/**
				 * ## Report Case Closed
				 */
				title: () => LocalizedString;
				/**
				 * The report opened by <@{userId}> has been closed.
				 */
				subtitle: (arg: { userId: string }) => LocalizedString;
				/**
				 * **Resolution Note**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_dm: {
				/**
				 * ## Your ticket has been closed
				 */
				title: () => LocalizedString;
				/**
				 * **Reason**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_dm_general: {
				/**
				 * ## Your general support ticket has been closed
				 */
				title: () => LocalizedString;
				/**
				 * **Reason**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_dm_billing: {
				/**
				 * ## Your billing ticket has been closed
				 */
				title: () => LocalizedString;
				/**
				 * If you still need help, open a new billing ticket and include your order details again.
				 */
				intro: () => LocalizedString;
				/**
				 * **Reason**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
			ticket_closed_dm_report: {
				/**
				 * ## Your report ticket has been closed
				 */
				title: () => LocalizedString;
				/**
				 * Staff reviewed the report and any attached evidence.
				 */
				intro: () => LocalizedString;
				/**
				 * **Resolution Note**: {reason}
				 **Claim**: {claimStatus}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: { claimStatus: string; reason: string; transcriptStatus: string }) => LocalizedString;
				/**
				 * -# _Closed by {closerName}_
				 */
				closed_by: (arg: { closerName: string }) => LocalizedString;
			};
		};
	};
	logs: {
		duration: {
			/**
			 * d
			 */
			day_short: () => LocalizedString;
			/**
			 * h
			 */
			hour_short: () => LocalizedString;
			/**
			 * m
			 */
			minute_short: () => LocalizedString;
			/**
			 * s
			 */
			second_short: () => LocalizedString;
		};
		templates: {
			ticket_created: {
				/**
				 * ## Ticket Created
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} opened {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **Created**: {createdAt}
				 **Reason**: {reason}
				 */
				details: (arg: {
					createdAt: string;
					createdByMention: string;
					reason: string;
					ticketId: string;
					ticketTypeName: string;
				}) => LocalizedString;
			};
			ticket_claimed: {
				/**
				 * ## Ticket Claimed
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} claimed {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **Open Age**: {ticketAge}
				 */
				details: (arg: {
					createdByMention: string;
					ticketAge: string;
					ticketId: string;
					ticketTypeName: string;
				}) => LocalizedString;
			};
			ticket_unclaimed: {
				/**
				 * ## Ticket Unclaimed
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} unclaimed {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **Open Age**: {ticketAge}
				 */
				details: (arg: {
					createdByMention: string;
					ticketAge: string;
					ticketId: string;
					ticketTypeName: string;
				}) => LocalizedString;
			};
			ticket_closed: {
				/**
				 * ## Ticket Closed
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} closed {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **Claim Status**: {claimStatus}
				 **Open Age**: {ticketAge}
				 **Reason**: {reason}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: {
					claimStatus: string;
					createdByMention: string;
					reason: string;
					ticketAge: string;
					ticketId: string;
					ticketTypeName: string;
					transcriptStatus: string;
				}) => LocalizedString;
			};
			ticket_reopened: {
				/**
				 * ## Ticket Reopened
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} reopened {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **Claim Status**: {claimStatus}
				 **Ticket Age**: {ticketAge}
				 */
				details: (arg: {
					claimStatus: string;
					createdByMention: string;
					ticketAge: string;
					ticketId: string;
					ticketTypeName: string;
				}) => LocalizedString;
			};
			ticket_deleted: {
				/**
				 * ## Ticket Deleted
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} deleted {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **Claim Status**: {claimStatus}
				 **Open Age**: {ticketAge}
				 **Close Reason**: {reason}
				 **Transcript**: {transcriptStatus}
				 */
				details: (arg: {
					claimStatus: string;
					createdByMention: string;
					reason: string;
					ticketAge: string;
					ticketId: string;
					ticketTypeName: string;
					transcriptStatus: string;
				}) => LocalizedString;
			};
			ticket_renamed: {
				/**
				 * ## Ticket Renamed
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} renamed {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 **From**: `{oldChannelName}`
				 **To**: `{newChannelName}`
				 */
				details: (arg: {
					createdByMention: string;
					newChannelName: string;
					oldChannelName: string;
					ticketId: string;
					ticketTypeName: string;
				}) => LocalizedString;
			};
			user_added: {
				/**
				 * ## User Added
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} added {targetMention} to {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; targetMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 */
				details: (arg: { createdByMention: string; ticketId: string; ticketTypeName: string }) => LocalizedString;
			};
			user_removed: {
				/**
				 * ## User Removed
				 */
				title: () => LocalizedString;
				/**
				 * {actorMention} removed {targetMention} from {ticketChannelMention}.
				 */
				action: (arg: { actorMention: string; targetMention: string; ticketChannelMention: string }) => LocalizedString;
				/**
				 * **Ticket**: #{ticketId} - {ticketTypeName}
				 **Opened By**: {createdByMention}
				 */
				details: (arg: { createdByMention: string; ticketId: string; ticketTypeName: string }) => LocalizedString;
			};
		};
	};
};

export type Formatters = {};
